package com.br.senai.ads3.agenda_fatesg.pages;


import com.br.senai.ads3.agenda_fatesg.domains.Contato;
import com.br.senai.ads3.agenda_fatesg.enums.TipoTela;
import java.awt.Color;
import java.io.FileWriter;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CLAYTON.MARQUES
 */
public class Form_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Form_Main
     * @param tipoela
     */
    
    final private TipoTela tipoTela;
    private Contato contato;
    
    public Form_Cadastro(final TipoTela tipoTela, final Contato contato ) {
        this.tipoTela = tipoTela;
        if(contato == null){
            this.contato = new Contato("","","");
        } else {
            this.contato = contato;
        }       
        initComponents();
        ajustaTela();
        carregaTela();
    }

    public Form_Cadastro() {
        this(TipoTela.INSERT, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(215, 63, 17));

        pnDados.setBackground(new java.awt.Color(82, 0, 30));
        pnDados.setForeground(new java.awt.Color(206, 118, 25));

        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setLabelFor(edtNome);
        lblNome.setText("Nome completo:");
        lblNome.setName("lblNome"); // NOI18N

        edtNome.setName("edtNome"); // NOI18N
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });

        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setLabelFor(edtTelefone);
        lblTelefone.setText("Telefone:");
        lblTelefone.setName("lblTelefone"); // NOI18N

        edtTelefone.setName("edtelefone"); // NOI18N

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setLabelFor(edtEmail);
        lblEmail.setText("E-mail:");
        lblEmail.setName("lblNome"); // NOI18N

        edtEmail.setName("edtNome"); // NOI18N

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(27, 27, 27)
                        .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(27, 27, 27)
                        .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(27, 27, 27)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agenda pessoal");

        btnGravar.setBackground(new java.awt.Color(24, 63, 17));
        btnGravar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(204, 255, 204));
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(102, 0, 0));
        btnFechar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 204, 204));
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        String nomeNovo = edtNome.getText().trim();
        String email = edtEmail.getText().trim();
        String telefone = edtTelefone.getText().trim();
        String status = "ativo";
        boolean isEdit = this.tipoTela == TipoTela.EDIT;
        java.io.File arquivo = new java.io.File("agenda.txt");

        try {
            // --- INÍCIO DA VALIDAÇÃO DE DUPLICIDADE ---
            // Se for Inserção: não pode coincidir com ninguém
            // Se for Edição: só valida se o usuário mudou o nome e o novo já existe
            if (this.tipoTela == TipoTela.INSERT || !nomeNovo.equalsIgnoreCase(this.contato.getNome())) {
                if (arquivo.exists()) {
                    List<String> todasLinhas = Files.readAllLines(arquivo.toPath());
                    for (String linha : todasLinhas) {
                        String[] registro = linha.split(";");
                        String nomeSalvo = registro[0];
                        if (nomeSalvo.equalsIgnoreCase(nomeNovo)) {
                            if(registro[3].equalsIgnoreCase("ativo")) {
                                JOptionPane.showMessageDialog(this, "Erro: O nome '" + nomeNovo + "' já está cadastrado!");
                                return; // Para a execução aqui
                            } else {
                                if(JOptionPane.showConfirmDialog(this, "Este contato está inativo. Deseja ativá-lo?") == JOptionPane.YES_OPTION){
                                    isEdit = true;
                                    this.contato.setNome(nomeNovo);
                                } else {
                                    return;
                                }
                            }
                        }
                    }
                }
            }
            // --- FIM DA VALIDAÇÃO ---

            // Lógica de gravação (Inserção ou Edição)
            if (!isEdit) {
                FileWriter fw = new FileWriter(arquivo, true);
                fw.write(nomeNovo.concat(";").concat(email).concat(";").concat(telefone).concat(";").concat(status).concat(System.lineSeparator()));
                fw.close();
            } else {
                java.util.List<String> linhas = Files.readAllLines(arquivo.toPath());
                for (int i = 0; i < linhas.size(); i++) {
                    if (linhas.get(i).startsWith(this.contato.getNome() + ";")) {
                        linhas.set(i, nomeNovo.concat(";").concat(email).concat(";").concat(telefone).concat(";").concat(status));
                        break;
                    }
                }
                Files.write(arquivo.toPath(), linhas);
            }

            JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
            new Form_Listagem().setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao processar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        new Form_Listagem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnDados;
    // End of variables declaration//GEN-END:variables

    private void ajustaTela() {
        boolean habilita = true;
        Color corTela = new Color(35,126,172);
        Color corBotao = new Color(24,63,17);
        if(this.tipoTela == TipoTela.VIEW){
            corTela = new Color(206,118,25);
            habilita = false;
        } else if(this.tipoTela == TipoTela.EDIT){
            corTela = new Color(82,0,30);
            corBotao = new Color(215,63,17);            
        }
        
        if(habilita){
            this.edtTelefone.setForeground(Color.black);
            this.edtEmail.setForeground(Color.black);
            this.edtNome.setForeground(Color.black);
        } else {
            this.edtTelefone.setForeground(Color.lightGray);
            this.edtEmail.setForeground(Color.lightGray);
            this.edtNome.setForeground(Color.lightGray);
        }
        this.pnDados.setBackground(corTela);
        this.btnGravar.setBackground(corBotao);
        this.btnGravar.setVisible(habilita);
        this.edtTelefone.setEnabled(habilita);        
        this.edtEmail.setEnabled(habilita);
        this.edtNome.setEnabled(habilita);
        
        this.revalidate();
        this.repaint();
    }

    private void carregaTela() {
        if(this.contato == null){
            this.contato = new Contato("", "", "");
        }
        this.edtNome.setText(this.contato.getNome());
        this.edtTelefone.setText(this.contato.getTelefone());
        this.edtEmail.setText(this.contato.getEmail());
    }
}
